### ISSUE TITLE
peer to peer Group code review

### ISSUE THREAD

**Issue by Hadi111jafari** [NeckerFree/To-Do-List#4]
Nice work, so far you have done hard work. but you still need to work on
[Optional]
- It would look good if you remove the outline of the input field, like outline: none:
- I suggest if you give some breading space for the input field, you may use padding ... for that

**Comment by Gnwin** [comment]
Good work. Try enhancing the UI.

**Comment by amrendrakind** [comment]
@amrendrakind: 

- You can consider breaking into more modules from the code of index.js 
- When I am inserting a new task whole screen got refreshed. You can have smooth insertion of tasks from UX point of view.

**Comment by NeckerFree** [comment]
Changes updated in To-Do List Review
